NEIGHBORHOODS_CABA = [
    "agronomía",
    "almagro",
    "balvanera",
    "barracas",
    "belgrano",
    "boedo",
    "caballito",
    "chacarita",
    "coghlan",
    "colegiales",
    "constitución",
    "flores",
    "floresta",
    "la boca",
    "la paternal",
    "liniers",
    "mataderos",
    "monte castro",
    "monserrat",
    "nueva pompeya",
    "núñez",
    "palermo",
    "parque avellaneda",
    "parque chacabuco",
    "parque chas",
    "parque patricios",
    "puerto madero",
    "recoleta",
    "retiro",
    "saavedra",
    "san cristóbal",
    "san nicolás",
    "san telmo",
    "vélez sarsfield",
    "versalles",
    "villa crespo",
    "villa del parque",
    "villa devoto",
    "villa general Mitre",
    "villa lugano",
    "villa luro",
    "villa ortúzar",
    "villa pueyrredón",
    "villa real",
    "villa riachuelo",
    "villa santa rita",
    "villa soldati",
    "villa urquiza"
]